import { NextResponse } from 'next/server';
import postgres from 'postgres';

/**
 * AURA WEEKLY SENTINEL REPORTER (v5.0)
 * Scheduled: Every Sunday at 00:00
 */
export async function GET(req: Request) {
  // CRON AUTH SECURITY
  const authHeader = req.headers.get('authorization');
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}` && process.env.NODE_ENV === 'production') {
    return new Response('Unauthorized', { status: 401 });
  }

  const sql = postgres(process.env.DATABASE_URL || '');
  const BREVO_KEY = process.env.BREVO_API_KEY;
  const RECIPIENT = "ramzendrum@gmail.com";

  try {
    console.log("🕒 Generating Weekly Intelligence Report...");

    // 1. PULL WEEKLY CHAT DATA
    const chatRows = await sql`
      SELECT user_id, content, metadata, created_at 
      FROM chat_histories 
      WHERE role = 'user' AND created_at > now() - interval '7 days'
      ORDER BY created_at DESC
    `;

    // 2. PULL WEEKLY KNOWLEDGE VARIANTS
    const cacheRows = await sql`
      SELECT query, answer FROM knowledge_cache 
      WHERE created_at > now() - interval '7 days'
    `;

    if (chatRows.length === 0) {
        console.log("ℹ️ No data to report this week.");
        return NextResponse.json({ status: "No data" });
    }

    // 3. COMPILE HTML REPORT
    let reportHtml = `
      <div style="font-family: sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
        <h2 style="color: #4F46E5; border-bottom: 2px solid #4F46E5; padding-bottom: 10px;">AURA Supreme Intelligence Report</h2>
        <p><strong>Period:</strong> Last 7 Days (Weekly Review)</p>
        
        <h3 style="color: #1F2937;">📊 Institutional Insights</h3>
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
          <tr style="background: #F9FAFB;">
            <th style="text-align: left; padding: 8px; border: 1px solid #ddd;">Category</th>
            <th style="text-align: left; padding: 8px; border: 1px solid #ddd;">Mood</th>
            <th style="text-align: left; padding: 8px; border: 1px solid #ddd;">Status</th>
          </tr>
          ${chatRows.slice(0, 10).map(r => `
            <tr>
              <td style="padding: 8px; border: 1px solid #ddd;">${r.metadata?.category || 'GENERAL'}</td>
              <td style="padding: 8px; border: 1px solid #ddd;">${r.metadata?.mood || 'NEUTRAL'}</td>
              <td style="padding: 8px; border: 1px solid #ddd;">${r.metadata?.cached ? '✅ CACHED ($0)' : '🔍 RAG SEARCH'}</td>
            </tr>
          `).join('')}
        </table>

        <h3 style="color: #1F2937;">🧠 New Knowledge Learned (Top 5)</h3>
        <ul style="padding-left: 20px;">
          ${cacheRows.slice(0, 5).map(c => `<li><strong>${c.query}</strong>: ${c.answer.substring(0, 50)}...</li>`).join('')}
        </ul>

        <div style="background: #EEF2FF; padding: 15px; border-radius: 8px; margin-top: 20px;">
          <p style="margin: 0; color: #4F46E5; font-weight: bold;">Weekly Efficiency Bonus:</p>
          <p style="margin: 0; font-size: 24px;">$${(chatRows.filter(r => r.metadata?.cached).length * 0.05).toFixed(2)} USD Saved</p>
        </div>
        
        <p style="font-size: 12px; color: #9CA3AF; margin-top: 30px; text-align: center;">
          Automatically generated by Aura Neural Sentinel Core.
        </p>
      </div>
    `;

    // 4. SEND VIA BREVO
    const response = await fetch("https://api.brevo.com/v3/smtp/email", {
      method: "POST",
      headers: {
        "accept": "application/json",
        "api-key": BREVO_KEY || '',
        "content-type": "application/json"
      },
      body: JSON.stringify({
        sender: { name: "Aura Sentinel", email: "aura@msajce-edu.in" },
        to: [{ email: RECIPIENT, name: "Ram" }],
        subject: `Weekly Institutional Intelligence: Aura MSAJCE`,
        htmlContent: reportHtml
      })
    });

    if (response.ok) {
        console.log("✅ Weekly Report Sent Successfully.");
        return NextResponse.json({ status: "Success" });
    } else {
        const err = await response.text();
        console.error("❌ Brevo Failed:", err);
        return NextResponse.json({ status: "Brevo Error", detail: err }, { status: 500 });
    }

  } catch (error) {
    console.error("❌ Cron Report Error:", error.message);
    return NextResponse.json({ status: "Internal Error" }, { status: 500 });
  }
}
